/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Log.h"
/* Header for class android_serialport_SerialPort */

#ifndef BEALEAD_SERIAL_PORT_H
#define BEALEAD_SERIAL_PORT_H

#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     org_bealead_serial_rs232_Rs232SerialPort
* Method:    open
* Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor
*/
//package org.bealead.alter.serial

JNIEXPORT jobject JNICALL
Java_com_seiko_serial_rs232_AbsSerialPort_deviceOpen(JNIEnv *env, jobject from,
                                               jstring path, jint rate,
                                               jint databits, jint stopbits, jint paritys);

/*
 * Class:     org_bealead_serial_rs232_Rs232SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_seiko_serial_rs232_AbsSerialPort_deviceClose(JNIEnv *env, jobject from);

/*
 * Class:     org_bealead_serial_rs232_Rs232SerialPort
 * Method:    setBaudRate
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_seiko_serial_rs232_AbsSerialPort_deviceBaudRate(JNIEnv *env, jobject from,
                                                   jint rate);

#ifdef __cplusplus
};
#endif

#endif //BEALEAD_SERIAL_PORT_H
